import { CountryEntity } from '../country/entities/country.entity';
import { CurrencyEntity } from '../currency/entities/currency.entity';
import { GenreEntity } from '../genre/entities/genre.entity';
import { LanguageEntity } from '../language/entities/language.entity';
import { MovieImageTypeEntity } from '../movie-image-type/entities/movie-image-type.entity';
import { MoviePersonTypeEntity } from '../movie-person-type/entities/movie-person-type.entity';

export const CURRENCIES: Pick<CurrencyEntity, 'id' | 'name' | 'symbol'>[] = [
  { id: 'USD', name: 'United States Dollar', symbol: '$' },
  { id: 'EUR', name: 'Euro', symbol: '€' },
  { id: 'RUB', name: 'Russian Ruble', symbol: '₽' },
  { id: 'GBP', name: 'British Pound', symbol: '£' },
  { id: 'JPY', name: 'Japanese Yen', symbol: '¥' },
  { id: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
  { id: 'INR', name: 'Indian Rupee', symbol: '₹' },
  { id: 'KRW', name: 'South Korean Won', symbol: '₩' },
];

export const LANGUAGES: Pick<LanguageEntity, 'id' | 'name'>[] = [
  { id: 'eng', name: 'English' },
  { id: 'rus', name: 'Russian' },
  { id: 'spa', name: 'Spanish' },
  { id: 'fra', name: 'French' },
  { id: 'deu', name: 'German' },
  { id: 'jpn', name: 'Japanese' },
  { id: 'zho', name: 'Chinese' },
  { id: 'hin', name: 'Hindi' },
  { id: 'ara', name: 'Arabic' },
  { id: 'por', name: 'Portuguese' },
  { id: 'kor', name: 'Korean' },
];

export const MOVIE_IMAGE_TYPES: Pick<MovieImageTypeEntity, 'name'>[] = [
  { name: 'poster' },
  { name: 'frame' },
  { name: 'promo' },
];

export const MOVIE_PERSON_TYPES: Pick<MoviePersonTypeEntity, 'name'>[] = [
  { name: 'actor' },
  { name: 'composer' },
  { name: 'designer' },
  { name: 'director' },
  { name: 'editor' },
  { name: 'operator' },
  { name: 'producer' },
  { name: 'screenwriter' },
  { name: 'voice actor' },
  { name: 'sound director' },
  { name: 'music editor' },
  { name: 'understudy' },
  { name: 'casting director' },
];

export const GENRES: Pick<GenreEntity, 'name'>[] = [
  { name: 'Action' },
  { name: 'Adventure' },
  { name: 'Animation' },
  { name: 'Comedy' },
  { name: 'Crime' },
  { name: 'Documentary' },
  { name: 'Drama' },
  { name: 'Family' },
  { name: 'Fantasy' },
  { name: 'History' },
  { name: 'Horror' },
  { name: 'Music' },
  { name: 'Mystery' },
  { name: 'Romance' },
  { name: 'Science Fiction' },
  { name: 'TV Movie' },
  { name: 'Thriller' },
  { name: 'War' },
  { name: 'Western' },
];

export const COUNTRIES: Pick<
  CountryEntity,
  'id' | 'name' | 'currencyId' | 'languageId'
>[] = [
  // Africa
  { id: 'DZ', name: 'Algeria', currencyId: 'USD', languageId: 'ara' },
  { id: 'AO', name: 'Angola', currencyId: 'USD', languageId: 'por' },
  { id: 'BJ', name: 'Benin', currencyId: 'USD', languageId: 'fra' },
  { id: 'BW', name: 'Botswana', currencyId: 'USD', languageId: 'eng' },
  { id: 'BF', name: 'Burkina Faso', currencyId: 'USD', languageId: 'fra' },
  { id: 'BI', name: 'Burundi', currencyId: 'USD', languageId: 'fra' },
  { id: 'CV', name: 'Cabo Verde', currencyId: 'USD', languageId: 'por' },
  { id: 'CM', name: 'Cameroon', currencyId: 'USD', languageId: 'fra' },
  {
    id: 'CF',
    name: 'Central African Republic',
    currencyId: 'USD',
    languageId: 'fra',
  },
  { id: 'TD', name: 'Chad', currencyId: 'USD', languageId: 'fra' },
  { id: 'KM', name: 'Comoros', currencyId: 'USD', languageId: 'ara' },
  { id: 'CG', name: 'Congo', currencyId: 'USD', languageId: 'fra' },
  {
    id: 'CD',
    name: 'Congo (Democratic Republic of the)',
    currencyId: 'USD',
    languageId: 'fra',
  },
  { id: 'CI', name: "Côte d'Ivoire", currencyId: 'USD', languageId: 'fra' },
  { id: 'DJ', name: 'Djibouti', currencyId: 'USD', languageId: 'fra' },
  { id: 'EG', name: 'Egypt', currencyId: 'USD', languageId: 'ara' },
  { id: 'GQ', name: 'Equatorial Guinea', currencyId: 'USD', languageId: 'spa' },
  { id: 'ER', name: 'Eritrea', currencyId: 'USD', languageId: 'eng' },
  { id: 'SZ', name: 'Eswatini', currencyId: 'USD', languageId: 'eng' },
  { id: 'ET', name: 'Ethiopia', currencyId: 'USD', languageId: 'eng' },
  { id: 'GA', name: 'Gabon', currencyId: 'USD', languageId: 'fra' },
  { id: 'GM', name: 'Gambia', currencyId: 'USD', languageId: 'eng' },
  { id: 'GH', name: 'Ghana', currencyId: 'USD', languageId: 'eng' },
  { id: 'GN', name: 'Guinea', currencyId: 'USD', languageId: 'fra' },
  { id: 'GW', name: 'Guinea-Bissau', currencyId: 'USD', languageId: 'por' },
  { id: 'KE', name: 'Kenya', currencyId: 'USD', languageId: 'eng' },
  { id: 'LS', name: 'Lesotho', currencyId: 'USD', languageId: 'eng' },
  { id: 'LR', name: 'Liberia', currencyId: 'USD', languageId: 'eng' },
  { id: 'LY', name: 'Libya', currencyId: 'USD', languageId: 'ara' },
  { id: 'MG', name: 'Madagascar', currencyId: 'USD', languageId: 'fra' },
  { id: 'MW', name: 'Malawi', currencyId: 'USD', languageId: 'eng' },
  { id: 'ML', name: 'Mali', currencyId: 'USD', languageId: 'fra' },
  { id: 'MR', name: 'Mauritania', currencyId: 'USD', languageId: 'ara' },
  { id: 'MU', name: 'Mauritius', currencyId: 'USD', languageId: 'eng' },
  { id: 'MA', name: 'Morocco', currencyId: 'USD', languageId: 'ara' },
  { id: 'MZ', name: 'Mozambique', currencyId: 'USD', languageId: 'por' },
  { id: 'NA', name: 'Namibia', currencyId: 'USD', languageId: 'eng' },
  { id: 'NE', name: 'Niger', currencyId: 'USD', languageId: 'fra' },
  { id: 'NG', name: 'Nigeria', currencyId: 'USD', languageId: 'eng' },
  { id: 'RW', name: 'Rwanda', currencyId: 'USD', languageId: 'eng' },
  {
    id: 'ST',
    name: 'Sao Tome and Principe',
    currencyId: 'USD',
    languageId: 'por',
  },
  { id: 'SN', name: 'Senegal', currencyId: 'USD', languageId: 'fra' },
  { id: 'SC', name: 'Seychelles', currencyId: 'USD', languageId: 'fra' },
  { id: 'SL', name: 'Sierra Leone', currencyId: 'USD', languageId: 'eng' },
  { id: 'SO', name: 'Somalia', currencyId: 'USD', languageId: 'ara' },
  { id: 'ZA', name: 'South Africa', currencyId: 'USD', languageId: 'eng' },
  { id: 'SS', name: 'South Sudan', currencyId: 'USD', languageId: 'eng' },
  { id: 'SD', name: 'Sudan', currencyId: 'USD', languageId: 'ara' },
  { id: 'TZ', name: 'Tanzania', currencyId: 'USD', languageId: 'eng' },
  { id: 'TG', name: 'Togo', currencyId: 'USD', languageId: 'fra' },
  { id: 'TN', name: 'Tunisia', currencyId: 'USD', languageId: 'ara' },
  { id: 'UG', name: 'Uganda', currencyId: 'USD', languageId: 'eng' },
  { id: 'ZM', name: 'Zambia', currencyId: 'USD', languageId: 'eng' },
  { id: 'ZW', name: 'Zimbabwe', currencyId: 'USD', languageId: 'eng' },

  // Asia
  { id: 'AF', name: 'Afghanistan', currencyId: 'USD', languageId: 'eng' },
  { id: 'AM', name: 'Armenia', currencyId: 'USD', languageId: 'eng' },
  { id: 'AZ', name: 'Azerbaijan', currencyId: 'USD', languageId: 'eng' },
  { id: 'BH', name: 'Bahrain', currencyId: 'USD', languageId: 'ara' },
  { id: 'BD', name: 'Bangladesh', currencyId: 'USD', languageId: 'eng' },
  { id: 'BT', name: 'Bhutan', currencyId: 'USD', languageId: 'eng' },
  { id: 'BN', name: 'Brunei', currencyId: 'USD', languageId: 'eng' },
  { id: 'KH', name: 'Cambodia', currencyId: 'USD', languageId: 'eng' },
  { id: 'CN', name: 'China', currencyId: 'CNY', languageId: 'zho' },
  { id: 'GE', name: 'Georgia', currencyId: 'USD', languageId: 'eng' },
  { id: 'IN', name: 'India', currencyId: 'INR', languageId: 'hin' },
  { id: 'ID', name: 'Indonesia', currencyId: 'USD', languageId: 'eng' },
  { id: 'IR', name: 'Iran', currencyId: 'USD', languageId: 'eng' },
  { id: 'IQ', name: 'Iraq', currencyId: 'USD', languageId: 'ara' },
  { id: 'IL', name: 'Israel', currencyId: 'USD', languageId: 'eng' },
  { id: 'JP', name: 'Japan', currencyId: 'JPY', languageId: 'jpn' },
  { id: 'JO', name: 'Jordan', currencyId: 'USD', languageId: 'ara' },
  { id: 'KZ', name: 'Kazakhstan', currencyId: 'USD', languageId: 'rus' },
  { id: 'KW', name: 'Kuwait', currencyId: 'USD', languageId: 'ara' },
  { id: 'KG', name: 'Kyrgyzstan', currencyId: 'USD', languageId: 'rus' },
  { id: 'LA', name: 'Laos', currencyId: 'USD', languageId: 'eng' },
  { id: 'LB', name: 'Lebanon', currencyId: 'USD', languageId: 'ara' },
  { id: 'MY', name: 'Malaysia', currencyId: 'USD', languageId: 'eng' },
  { id: 'MV', name: 'Maldives', currencyId: 'USD', languageId: 'eng' },
  { id: 'MN', name: 'Mongolia', currencyId: 'USD', languageId: 'eng' },
  { id: 'MM', name: 'Myanmar', currencyId: 'USD', languageId: 'eng' },
  { id: 'NP', name: 'Nepal', currencyId: 'USD', languageId: 'eng' },
  { id: 'KP', name: 'North Korea', currencyId: 'USD', languageId: 'kor' },
  { id: 'OM', name: 'Oman', currencyId: 'USD', languageId: 'ara' },
  { id: 'PK', name: 'Pakistan', currencyId: 'USD', languageId: 'eng' },
  { id: 'PH', name: 'Philippines', currencyId: 'USD', languageId: 'eng' },
  { id: 'QA', name: 'Qatar', currencyId: 'USD', languageId: 'ara' },
  { id: 'SA', name: 'Saudi Arabia', currencyId: 'USD', languageId: 'ara' },
  { id: 'SG', name: 'Singapore', currencyId: 'USD', languageId: 'zho' },
  { id: 'KR', name: 'South Korea', currencyId: 'KRW', languageId: 'kor' },
  { id: 'LK', name: 'Sri Lanka', currencyId: 'USD', languageId: 'eng' },
  { id: 'SY', name: 'Syria', currencyId: 'USD', languageId: 'ara' },
  { id: 'TW', name: 'Taiwan', currencyId: 'USD', languageId: 'zho' },
  { id: 'TJ', name: 'Tajikistan', currencyId: 'USD', languageId: 'rus' },
  { id: 'TH', name: 'Thailand', currencyId: 'USD', languageId: 'eng' },
  { id: 'TR', name: 'Turkey', currencyId: 'USD', languageId: 'eng' },
  { id: 'TM', name: 'Turkmenistan', currencyId: 'USD', languageId: 'rus' },
  {
    id: 'AE',
    name: 'United Arab Emirates',
    currencyId: 'USD',
    languageId: 'ara',
  },
  { id: 'UZ', name: 'Uzbekistan', currencyId: 'USD', languageId: 'rus' },
  { id: 'VN', name: 'Vietnam', currencyId: 'USD', languageId: 'eng' },
  { id: 'YE', name: 'Yemen', currencyId: 'USD', languageId: 'ara' },

  // Europe
  { id: 'AL', name: 'Albania', currencyId: 'EUR', languageId: 'eng' },
  { id: 'AD', name: 'Andorra', currencyId: 'EUR', languageId: 'spa' },
  { id: 'AT', name: 'Austria', currencyId: 'EUR', languageId: 'deu' },
  { id: 'BY', name: 'Belarus', currencyId: 'RUB', languageId: 'rus' },
  { id: 'BE', name: 'Belgium', currencyId: 'EUR', languageId: 'fra' },
  {
    id: 'BA',
    name: 'Bosnia and Herzegovina',
    currencyId: 'EUR',
    languageId: 'eng',
  },
  { id: 'BG', name: 'Bulgaria', currencyId: 'EUR', languageId: 'eng' },
  { id: 'HR', name: 'Croatia', currencyId: 'EUR', languageId: 'eng' },
  { id: 'CY', name: 'Cyprus', currencyId: 'EUR', languageId: 'eng' },
  { id: 'CZ', name: 'Czech Republic', currencyId: 'EUR', languageId: 'eng' },
  { id: 'DK', name: 'Denmark', currencyId: 'EUR', languageId: 'eng' },
  { id: 'EE', name: 'Estonia', currencyId: 'EUR', languageId: 'eng' },
  { id: 'FI', name: 'Finland', currencyId: 'EUR', languageId: 'eng' },
  { id: 'FR', name: 'France', currencyId: 'EUR', languageId: 'fra' },
  { id: 'DE', name: 'Germany', currencyId: 'EUR', languageId: 'deu' },
  { id: 'GR', name: 'Greece', currencyId: 'EUR', languageId: 'eng' },
  { id: 'HU', name: 'Hungary', currencyId: 'EUR', languageId: 'eng' },
  { id: 'IS', name: 'Iceland', currencyId: 'EUR', languageId: 'eng' },
  { id: 'IE', name: 'Ireland', currencyId: 'EUR', languageId: 'eng' },
  { id: 'IT', name: 'Italy', currencyId: 'EUR', languageId: 'eng' },
  { id: 'LV', name: 'Latvia', currencyId: 'EUR', languageId: 'eng' },
  { id: 'LI', name: 'Liechtenstein', currencyId: 'EUR', languageId: 'deu' },
  { id: 'LT', name: 'Lithuania', currencyId: 'EUR', languageId: 'eng' },
  { id: 'LU', name: 'Luxembourg', currencyId: 'EUR', languageId: 'fra' },
  { id: 'MT', name: 'Malta', currencyId: 'EUR', languageId: 'eng' },
  { id: 'MD', name: 'Moldova', currencyId: 'EUR', languageId: 'rus' },
  { id: 'MC', name: 'Monaco', currencyId: 'EUR', languageId: 'fra' },
  { id: 'ME', name: 'Montenegro', currencyId: 'EUR', languageId: 'eng' },
  { id: 'NL', name: 'Netherlands', currencyId: 'EUR', languageId: 'eng' },
  { id: 'MK', name: 'North Macedonia', currencyId: 'EUR', languageId: 'eng' },
  { id: 'NO', name: 'Norway', currencyId: 'EUR', languageId: 'eng' },
  { id: 'PL', name: 'Poland', currencyId: 'EUR', languageId: 'eng' },
  { id: 'PT', name: 'Portugal', currencyId: 'EUR', languageId: 'por' },
  { id: 'RO', name: 'Romania', currencyId: 'EUR', languageId: 'eng' },
  { id: 'RU', name: 'Russia', currencyId: 'RUB', languageId: 'rus' },
  { id: 'SM', name: 'San Marino', currencyId: 'EUR', languageId: 'eng' },
  { id: 'RS', name: 'Serbia', currencyId: 'EUR', languageId: 'eng' },
  { id: 'SK', name: 'Slovakia', currencyId: 'EUR', languageId: 'eng' },
  { id: 'SI', name: 'Slovenia', currencyId: 'EUR', languageId: 'eng' },
  { id: 'ES', name: 'Spain', currencyId: 'EUR', languageId: 'spa' },
  { id: 'SE', name: 'Sweden', currencyId: 'EUR', languageId: 'eng' },
  { id: 'CH', name: 'Switzerland', currencyId: 'EUR', languageId: 'deu' },
  { id: 'UA', name: 'Ukraine', currencyId: 'EUR', languageId: 'rus' },
  { id: 'GB', name: 'United Kingdom', currencyId: 'GBP', languageId: 'eng' },
  { id: 'VA', name: 'Vatican City', currencyId: 'EUR', languageId: 'eng' },

  // North America
  {
    id: 'AG',
    name: 'Antigua and Barbuda',
    currencyId: 'USD',
    languageId: 'eng',
  },
  { id: 'BS', name: 'Bahamas', currencyId: 'USD', languageId: 'eng' },
  { id: 'BB', name: 'Barbados', currencyId: 'USD', languageId: 'eng' },
  { id: 'BZ', name: 'Belize', currencyId: 'USD', languageId: 'eng' },
  { id: 'CA', name: 'Canada', currencyId: 'USD', languageId: 'eng' },
  { id: 'CR', name: 'Costa Rica', currencyId: 'USD', languageId: 'spa' },
  { id: 'CU', name: 'Cuba', currencyId: 'USD', languageId: 'spa' },
  { id: 'DM', name: 'Dominica', currencyId: 'USD', languageId: 'eng' },
  {
    id: 'DO',
    name: 'Dominican Republic',
    currencyId: 'USD',
    languageId: 'spa',
  },
  { id: 'SV', name: 'El Salvador', currencyId: 'USD', languageId: 'spa' },
  { id: 'GD', name: 'Grenada', currencyId: 'USD', languageId: 'eng' },
  { id: 'GT', name: 'Guatemala', currencyId: 'USD', languageId: 'spa' },
  { id: 'HT', name: 'Haiti', currencyId: 'USD', languageId: 'fra' },
  { id: 'HN', name: 'Honduras', currencyId: 'USD', languageId: 'spa' },
  { id: 'JM', name: 'Jamaica', currencyId: 'USD', languageId: 'eng' },
  { id: 'MX', name: 'Mexico', currencyId: 'USD', languageId: 'spa' },
  { id: 'NI', name: 'Nicaragua', currencyId: 'USD', languageId: 'spa' },
  { id: 'PA', name: 'Panama', currencyId: 'USD', languageId: 'spa' },
  {
    id: 'KN',
    name: 'Saint Kitts and Nevis',
    currencyId: 'USD',
    languageId: 'eng',
  },
  { id: 'LC', name: 'Saint Lucia', currencyId: 'USD', languageId: 'eng' },
  {
    id: 'VC',
    name: 'Saint Vincent and the Grenadines',
    currencyId: 'USD',
    languageId: 'eng',
  },
  {
    id: 'TT',
    name: 'Trinidad and Tobago',
    currencyId: 'USD',
    languageId: 'eng',
  },
  { id: 'US', name: 'United States', currencyId: 'USD', languageId: 'eng' },

  // Oceania
  { id: 'AU', name: 'Australia', currencyId: 'USD', languageId: 'eng' },
  { id: 'FJ', name: 'Fiji', currencyId: 'USD', languageId: 'eng' },
  { id: 'KI', name: 'Kiribati', currencyId: 'USD', languageId: 'eng' },
  { id: 'MH', name: 'Marshall Islands', currencyId: 'USD', languageId: 'eng' },
  { id: 'FM', name: 'Micronesia', currencyId: 'USD', languageId: 'eng' },
  { id: 'NR', name: 'Nauru', currencyId: 'USD', languageId: 'eng' },
  { id: 'NZ', name: 'New Zealand', currencyId: 'USD', languageId: 'eng' },
  { id: 'PW', name: 'Palau', currencyId: 'USD', languageId: 'eng' },
  { id: 'PG', name: 'Papua New Guinea', currencyId: 'USD', languageId: 'eng' },
  { id: 'WS', name: 'Samoa', currencyId: 'USD', languageId: 'eng' },
  { id: 'SB', name: 'Solomon Islands', currencyId: 'USD', languageId: 'eng' },
  { id: 'TO', name: 'Tonga', currencyId: 'USD', languageId: 'eng' },
  { id: 'TV', name: 'Tuvalu', currencyId: 'USD', languageId: 'eng' },
  { id: 'VU', name: 'Vanuatu', currencyId: 'USD', languageId: 'eng' },

  // South America
  { id: 'AR', name: 'Argentina', currencyId: 'USD', languageId: 'spa' },
  { id: 'BO', name: 'Bolivia', currencyId: 'USD', languageId: 'spa' },
  { id: 'BR', name: 'Brazil', currencyId: 'USD', languageId: 'por' },
  { id: 'CL', name: 'Chile', currencyId: 'USD', languageId: 'spa' },
  { id: 'CO', name: 'Colombia', currencyId: 'USD', languageId: 'spa' },
  { id: 'EC', name: 'Ecuador', currencyId: 'USD', languageId: 'spa' },
  { id: 'GY', name: 'Guyana', currencyId: 'USD', languageId: 'eng' },
  { id: 'PY', name: 'Paraguay', currencyId: 'USD', languageId: 'spa' },
  { id: 'PE', name: 'Peru', currencyId: 'USD', languageId: 'spa' },
  { id: 'SR', name: 'Suriname', currencyId: 'USD', languageId: 'eng' },
  { id: 'UY', name: 'Uruguay', currencyId: 'USD', languageId: 'spa' },
  { id: 'VE', name: 'Venezuela', currencyId: 'USD', languageId: 'spa' },
];
